version: '3.1'
services:
  rabbit-mq:
    image: rabbitmq:3.12.6-management
    container_name: rabbit-mq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./docker/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest